# Generated by Django 2.2.5 on 2019-10-09 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranklist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
